=== askhatkenenbay/kz/Java/Java_XML_XSD_Parsing/Bank.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/Banks"
        xmlns:tns="http://www.example.com/Banks">
    <element name="banks">
        <complexType>
            <sequence>
                <element name="bank" type="tns:Bank" minOccurs="16" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Bank">
        <all>
            <element name="amount-on-deposit" type="positiveInteger"/>
            <element name="profitability" type="tns:Profitability"/>
            <element name="time-constraints" type="tns:Time-constraints"/>
        </all>
        <attribute name="name" type="tns:Name" use="required"/>
        <attribute name="country" type="tns:Country" use="optional" default="Kazakhstan"/>
        <attribute name="type" type="string" use="required" default="до востребования">
            <simpleType>
                <restriction>
                    <enumeration value="до востребования"/>
                    <enumeration value="срочный"/>
                    <enumeration value="расчетный"/>
                    <enumeration value="накопительный"/>
                    <enumeration value="сберегательный"/>
                    <enumeration value="металлический"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="depositor" type="string" use="optional" default="Default Depositor"/>
        <attribute name="account-id" type="tns:Account-id" use="required"/>
    </complexType>

    <simpleType name="Name">
        <restriction base="ID">
            <pattern value="[A-Z][a-z]{1,15}"/>
        </restriction>
    </simpleType>

    <simpleType name="Country">
        <restriction>
            <pattern value="[A-Z]{2,3}|[A-Z][a-z]{2,15}"/>
        </restriction>
    </simpleType>

    <simpleType name="Account-id">
        <restriction base="ID">
            <pattern value="([0-9]{4}\\s){3}[0-9]{4}"/>
        </restriction>
    </simpleType>

    <simpleType name="Profitability">
        <restriction>
            <pattern value="100|100\\.0|[0-9][0-9]\\.[0-9]{0,3}|[0-9]\\.[0-9]{0,3}|[0-9]{1,2}"/>
        </restriction>
    </simpleType>

    <complexType name="Time-constraints">
        <sequence>
            <element name="years" type="tns:Years"/>
            <element name="months" type="tns:Months"/>
            <element name="days" type="tns:Days"/>
        </sequence>
    </complexType>

    <simpleType name="Years">
        <restriction>
            <!-- between 1 year to 25 years -->
            <pattern value="[1-9]|1[0-9]|2[0-5]"/>
        </restriction>
    </simpleType>

    <simpleType name="Months">
        <restriction>
            <!--between 1 month to 12 months -->
            <pattern value="[1-9]|1[012]"/>
        </restriction>
    </simpleType>

    <simpleType name="Days">
        <restriction>
            <!-- between 1 day to 31 days-->
            <pattern value="[1-9]|[12][0-9]|3[01]"/>
        </restriction>
    </simpleType>

</schema>

=== askhatkenenbay/kz/Java/Java_XML_XSD_Parsing/Bank.xml
<?xml version= "1.0" encoding="UTF-8" ?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.example.com/banks"
       xsi:schemaLocation="http://www.example.com/banks bank.xsd">

    <!-- 1 -->
    <bank name="Kaspi" country="Kazakhstan" type="расчетный" account-id="4789 5214 3240 2128" depositor="Billy">
        <amount-on-deposit>7878</amount-on-deposit>
        <profitability>12.7</profitability>
        <time-constraints>
            <years>3</years>
            <months>6</months>
            <days>10</days>
        </time-constraints>
    </bank>
    <!-- 2 -->
    <bank name="Halyk" country="Kazakhstan" type="до востребования" account-id="4159 5648 2078 1432" depositor="Tommy">
        <amount-on-deposit>1188</amount-on-deposit>
        <profitability>13.5</profitability>
        <time-constraints>
            <years>10</years>
            <months>1</months>
            <days>5</days>
        </time-constraints>
    </bank>
    <!-- 3 -->
    <bank name="Santander" country="Spain" type="срочный" account-id="7814 5621 4209 7432" depositor="Alejandro">
        <amount-on-deposit>2514</amount-on-deposit>
        <profitability>11.2</profitability>
        <time-constraints>
            <years>5</years>
            <months>4</months>
            <days>15</days>
        </time-constraints>
    </bank>
    <!-- 4 -->
    <bank name="Sberbank" country="Russia" type="расчетный" account-id="5641 2114 8745 2364" depositor="Vlad">
        <amount-on-deposit>2233</amount-on-deposit>
        <profitability>12.6</profitability>
        <time-constraints>
            <years>6</years>
            <months>7</months>
            <days>21</days>
        </time-constraints>
    </bank>
    <!-- 5 -->
    <bank name="Paribas" country="France" type="накопительный" account-id="1274 5624 8531 7509" depositor="Amy">
        <amount-on-deposit>3344</amount-on-deposit>
        <profitability>14.2</profitability>
        <time-constraints>
            <years>8</years>
            <months>4</months>
            <days>9</days>
        </time-constraints>
    </bank>
    <!-- 6 -->
    <bank name="Lloyds" country="UK" type="сберегательный" account-id="3214 5207 4963 2148" depositor="Emma">
        <amount-on-deposit>8888</amount-on-deposit>
        <profitability>10.1</profitability>
        <time-constraints>
            <years>4</years>
            <months>10</months>
            <days>0</days>
        </time-constraints>
    </bank>
    <!-- 7 -->
    <bank name="ING" country="Netherland" type="металлический" account-id="7462 1548 6238 9854" depositor="Kyler">
        <amount-on-deposit>4556</amount-on-deposit>
        <profitability>9.87</profitability>
        <time-constraints>
            <years>2</years>
            <months>2</months>
            <days>27</days>
        </time-constraints>
    </bank>
    <!-- 8 -->
    <bank name="UBS" country="Switzerland" type="сберегательный" account-id="2145 6845 7462 3087" depositor="Zosa">
        <amount-on-deposit>4778</amount-on-deposit>
        <profitability>10.2</profitability>
        <time-constraints>
            <years>3</years>
            <months>11</months>
            <days>14</days>
        </time-constraints>
    </bank>
    <!-- 9 -->
    <bank name="Intesa" country="Italy" type="накопительный" account-id="4721 3256 4812 9154" depositor="Sica">
        <amount-on-deposit>5123</amount-on-deposit>
        <profitability>11.1</profitability>
        <time-constraints>
            <years>5</years>
            <months>9</months>
            <days>3</days>
        </time-constraints>
    </bank>
    <!-- 10 -->
    <bank name="BBVA" country="Spain" type="расчетный" account-id="5647 1287 4930 8543" depositor="Carlos">
        <amount-on-deposit>3982</amount-on-deposit>
        <profitability>12.2</profitability>
        <time-constraints>
            <years>7</years>
            <months>1</months>
            <days>13</days>
        </time-constraints>
    </bank>
    <!-- 11 -->
    <bank name="Barclays" country="UK" type="до востребования" account-id="4712 5418 6574 3281" depositor="Olivia">
        <amount-on-deposit>7799</amount-on-deposit>
        <profitability>10.5</profitability>
        <time-constraints>
            <years>4</years>
            <months>10</months>
            <days>24</days>
        </time-constraints>
    </bank>
    <!-- 12 -->
    <bank name="Tsesnabank" country="Kazakhstan" type="металлический" account-id="4159 7856 2145 2841"
          depositor="Gulsara">
        <amount-on-deposit>1232</amount-on-deposit>
        <profitability>11.5</profitability>
        <time-constraints>
            <years>5</years>
            <months>3</months>
            <days>5</days>
        </time-constraints>
    </bank>
    <!-- 13 -->
    <bank name="Fortebank" country="Kazakhstan" type="до востребования" account-id="4562 4587 1265 8564"
          depositor="Madi">
        <amount-on-deposit>2145</amount-on-deposit>
        <profitability>11.9</profitability>
        <time-constraints>
            <years>6</years>
            <months>7</months>
            <days>21</days>
        </time-constraints>
    </bank>
    <!-- 14 -->
    <bank name="Altyn" country="China" type="расчетный" account-id="4157 4215 5624 8472" depositor="Marat">
        <amount-on-deposit>1558</amount-on-deposit>
        <profitability>12.1</profitability>
        <time-constraints>
            <years>4</years>
            <months>12</months>
            <days>14</days>
        </time-constraints>
    </bank>
    <!-- 15 -->
    <bank name="Eurasian" country="Kazakhstan" type="металлический" account-id="4578 2658 4153 6524" depositor="Nurai">
        <amount-on-deposit>3225</amount-on-deposit>
        <profitability>12.6</profitability>
        <time-constraints>
            <years>7</years>
            <months>2</months>
            <days>4</days>
        </time-constraints>
    </bank>
    <!-- 16 -->
    <bank name="Nurbank" country="Kazakhstan" type="расчетный" account-id="4147 4562 5687 5127" depositor="Raimbek">
        <amount-on-deposit>4512</amount-on-deposit>
        <profitability>10.8</profitability>
        <time-constraints>
            <years>8</years>
            <months>2</months>
            <days>19</days>
        </time-constraints>
    </bank>
</banks>
